################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c \
/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c 

OBJS += \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_cortex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_dma.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_gpio.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_i2c.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_spi.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim_ex.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart.o \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart_ex.o 

C_DEPS += \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_cortex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_dma.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_gpio.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_i2c.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_spi.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim_ex.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart.d \
./Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart_ex.d 


# Each subdirectory must supply rules for building sources it contributes
Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_adc_ex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_adc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_cortex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_cortex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_dma.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_dma.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_gpio.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_gpio.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_i2c.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_i2c.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_pwr_ex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_pwr_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rcc_ex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rcc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_rtc_ex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_rtc_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_spi.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_spi.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_tim_ex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_tim_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '

Drivers/STM32L0xx_HAL_Driver/stm32l0xx_hal_uart_ex.o: /Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Src/stm32l0xx_hal_uart_ex.c
	@echo 'Building file: $<'
	@echo 'Invoking: MCU GCC Compiler'
	@echo $(PWD)
	arm-none-eabi-gcc -mcpu=cortex-m0plus -mthumb -mfloat-abi=soft -DSTM32L072xx -DUSE_B_L072Z_LRWAN1 -DUSE_HAL_DRIVER -DREGION_EU868 -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Projects/Multi/Applications/LoRa/End_Node/inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/MLM32L07X01" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/STM32L0xx_HAL_Driver/Inc" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Device/ST/STM32L0xx/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/CMSIS/Include" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Crypto" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Phy" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Utilities" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Core" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/Common" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/hts221" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps22hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/lps25hb" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/Components/sx1276" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/X_NUCLEO_IKS01A2" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Drivers/BSP/B-L072Z-LRWAN1" -I"/Users/kevinvdm/Downloads/STM32CubeExpansion_LRWAN_V1.1.2/Middlewares/Third_Party/Lora/Mac/region"  -Os -g3 -Wall -fmessage-length=0 -ffunction-sections -c -fmessage-length=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


